### ISSUE TITLE
add button close

### ISSUE THREAD

**Issue by gonzasylv** [ItsOnlyBinary/kiwiirc-plugin-radio#1]
hi @ItsOnlyBinary ,

would have to add a button to close the window of the list of radios, on mobile when we open the window we can not come back on the chat.

Thanks

**Comment by ItsOnlyBinary** [comment]
I have refactored this plugin to a single html file and fixed #1 and #2 
it can now be found here: https://github.com/ItsOnlyBinary/my-kiwiirc-plugins

**Comment by gonzasylv** [comment]
Its perfect , thanks !
